Voyage_Proj/Users/urls.py
from django.urls import path
from Users import views


urlpatterns = [
    path('signup',views.SignUp, name = 'signup'),
    path('login',views.Login, name = 'login'),
    path('logout',views.logout,name='logout'),
    # path('profile',views.profile, name = 'profile'),
    

]

Voyage_Proj/Voyage_LandingApp/urls.py
from django.urls import path
from Voyage_LandingApp import views

urlpatterns = [
    path('',views.home_view, name = 'home'),
    path('Enquiry-Form', views.Enquiry_View, name = 'Enquiry_Form'),
    path('Contact',views.Contact_View, name = 'Contact'),
    path('AboutUs',views.AboutUs_View, name = 'AboutUs'),
    path('Search-Wiki', views.search_places_wiki_veiw, name = 'Search_Wiki'),

]


Voyage_Proj/Voyage_Proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views  # for reset password 
from django.urls import path,include
from django.conf.urls.static import static
from Users import urls
from Voyage_LandingApp import urls
from Holidays import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Voyage_LandingApp.urls')),
    path('',include('Holidays.urls')),
    path('',include('Users.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # accounts for authentication

    # password reset setting urls 
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='Users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='Users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='Users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='Users/password_reset_complete.html'),name='password_reset_complete'),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)




Voyage_Proj/Voyage_LandingApp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.conf import settings


class Enquiry_Tab(models.Model):
    Full_Name      = models.CharField(max_length=129)
    Email          = models.EmailField(max_length=159)
    Phone          = models.CharField(max_length=12,validators = [RegexValidator(r'^\d{1,12}$')], default = '')
    Journey_Date   = models.DateField(default = '')
    Destination    = models.CharField(max_length=129)
    Adults         = models.PositiveIntegerField(default = 0, help_text = 'People')


# Journey_Date

Voyage_Proj/Voyage_LandingApp/forms.py
from django import forms
from .models import Enquiry_Tab



class Enquiry_Form(forms.ModelForm):
    class Meta:
        model  = Enquiry_Tab
        fields = '__all__'
        widgets = {
                    'Full_Name'     : forms.TextInput(attrs={'placeholder': 'FullName'}),
                    'Email'         : forms.TextInput(attrs={'placeholder': 'Email'}),
                    'Phone'         : forms.TextInput(attrs={'placeholder': 'Phone'}),
                    'Journey_Date'  : forms.TextInput(attrs = {'type': 'date'}),
                    'Destination'   : forms.TextInput(attrs={'placeholder': 'Destination'}),
                    # 'Adults'        : forms.TextInput(attrs={'placeholder': 'People'}),

                    }



Voyage_Proj/Voyage_LandingApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Enquiry_Tab
from Holidays.models import(Holidays_Packages_Upload,Domestic_Holiday_Package,Central_Asia_Packages,   
                            Europe_Packages,
                            Middle_East_Packages,
                            SouthEast_Asia_Packages,
                            ) #importing holidays app models for counting the packages 
from .forms import Enquiry_Form
from django.template.loader import get_template
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.template import Context
import wikipedia
import requests






def home_view(request):
    Domestic_count    = Domestic_Holiday_Package.objects.all().count()
    CentralAsia_Count = Central_Asia_Packages.objects.all().count()
    Europe_count      = Europe_Packages.objects.all().count()
    MiddleEast_count  = Middle_East_Packages.objects.all().count()
    SouthEast_Asia_count = SouthEast_Asia_Packages.objects.all().count()
    template_name = 'Voyage_LandingApp/home.html'
    context    = {
                 'Domestic_count':Domestic_count,
                 'CentralAsia_Count':CentralAsia_Count,
                 'Europe_count':Europe_count,
                 'MiddleEast_count':MiddleEast_count,
                 'SouthEast_Asia_count':SouthEast_Asia_count,
                 }
    return render(request,template_name,context)

@login_required
def Enquiry_View(request):
    if request.method == 'POST':
        Form   = Enquiry_Form(request.POST or None)
        if Form.is_valid():
            name        = Form.cleaned_data['Full_Name']
            email       = Form.cleaned_data['Email']
            phone       = Form.cleaned_data['Phone']
            j_Date      = Form.cleaned_data['Journey_Date']
            print(j_Date)
            destination = Form.cleaned_data['Destination']
            people      = Form.cleaned_data['Adults']
            subject     = 'A New Traveller Posted His Details For Package..'
            context     = {
                            'name':name,
                            'email':email,
                            'phone':phone,
                            'j_Date':j_Date,
                            'destination':destination,
                            'people':people,
                          }
            voyage_email = 'voyageandholidayz@gmail.com'
            from_email   = voyage_email
            to           = [voyage_email,]
            message = get_template('Voyage_LandingApp/Enquiry_email.html').render(context)
            msg = EmailMessage(subject, message, to=to,from_email = from_email)
            msg.content_subtype  = 'html'
            msg.send() 
            Form.save()
            messages.success(request,'Done!, We Will Contact You Soon')
            return redirect('home')
    else:
        Form = Enquiry_Form()
    template   = 'Voyage_LandingApp/Enquiry_Form.html'
    context    =  {
                   'Form':Form,
                   }
    return render(request,template,context)



def Contact_View(request):
    if request.method == 'POST':
        firstname = request.POST['firstName']
        lastname  = request.POST['lastName']
        email     = request.POST['email']
        phone     = request.POST['phone']
        msg       = request.POST['message']
        subject        = 'Some One Contacted You From voyage Holidayz'
        context        = {
                            'firstname':firstname,
                            'lastname':lastname,
                            'email':email,
                            'phone':phone,
                            'msg':msg,
                            }
        voyage_email    = 'voyageandholidayz@gmail.com'
        from_email      = voyage_email
        to              =[voyage_email,]
        message         = get_template('Voyage_LandingApp/Contact_email.html').render(context)
        msg             = EmailMessage(subject,message,to=to,from_email=from_email,)
        msg.content_subtype = 'html'
        msg.send()
        return redirect('home')
    template = 'Voyage_LandingApp/Contact_View.html'
    return render(request,template)


# about us page 
def AboutUs_View(request):
    template = 'Voyage_LandingApp/AboutUs.html'
    return render(request,template)


# def search_places_wiki_veiw(request):
#     '''if end user search any thing in search box it will fetched the data from wikipedia '''


#     template = 'Voyage_LandingApp/Search_wiki.html'
#     if request.method == 'POST':
#         search_name = request.POST['wiki_name']
#         try:
#             search = wikipedia.page(search_name)
#         except wikipedia.exceptions.DisambiguationError as e:
#             print(e)
#         page_Data = search.summary
#         fomatted_data = page_Data.split('.')
#         all_images = search.images
#         new_images = []
#         for image in all_images:
#             if image.endswith('.jpg') or image.endswith('.png') or image.endswith('.jpeg'):
#                 new_images.append(image)   
#             else:
#                 print('not jpg image==================>')
                
#         context  = {
#                     'search':search,
#                     'new_images':new_images,
#                     # 'all_images':all_images,
#                     'fomatted_data':fomatted_data,
#                     }
#     return render(request, template,context)

def search_places_wiki_veiw(request):
    '''if end user search any thing in search box it will fetched the data from wikipedia '''
    template = 'Voyage_LandingApp/Search_wiki.html'
    options = None
    new_images = []
    fomatted_data = None
    page_id = None
    connection_Err = None
    if request.method == 'POST':
        search_name = request.POST['wiki_name']
        wiki_name   = search_name.strip()
        try:
            searched_Data = wikipedia.page(wiki_name,auto_suggest=False,redirect=True)
            page_Data     = searched_Data.summary
            fomatted_data = page_Data.split('.')
            all_images = searched_Data.images
            for image in all_images:
                if image.endswith('.jpg') or image.endswith('.png') or image.endswith('.jpeg'):
                    new_images.append(image)   
                else:
                    print('===============> not jpg,png,jpeg image..')
        except wikipedia.exceptions.PageError as e:
            page_id = e
        except requests.exceptions.ConnectionError as e:
            connection_Err = e
            print(connection_Err)
        except wikipedia.exceptions.DisambiguationError as e:
            options = e.options
    context = {
                'options':options,
                'new_images':new_images,
                'fomatted_data':fomatted_data,
                'page_id':page_id,
              } 
    return render(request, template,context)


# exception for timeout
# requests.exceptions.ConnectionError:
# requests.exceptions.ConnectionError: HTTPConnectionPool

Voyage_Proj/templates/Voyage_LandingApp/AboutUs.html
<!DOCTYPE html>
{% extends 'Voyage_LandingApp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"> -->
<header class="masthead" style="margin-top:-3%;padding-top:5%">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-7 py-5">
                <h1 class="mb-4">Voyage Holidayz </h1>
                <h2 class="m-0">Since 2008, Voyage Holidayz has been focused on bringing our customers the best in esteem and quality travel plans. </h2><br>
                <small class="text-white">
                    We offer best limits on our top rated visit bundles to clients who pick our viable administrations 
                    over and over. How about we remind you indeed that we don’t expect to be your visit and travel
                    specialists; we endeavor to be your vacation accomplices until the end of time
                </small><br>
                <strong> We likewise have journey occasions for individuals who are searching for solace and reasonable extravagance</strong>
            </div>
            <div class="col-lg-5">
                <div class="py-5 px-4 masthead-cards">
                    <div class="d-flex">
                        <a href="{% url 'Flight_Booking' %}" class="w-50 pr-3 pb-4">
                            <div class="card border-0 border-bottom-red shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <i class="fas fa-plane-departure fa-4x my-2"></i>
                                        <!-- <i class="fa fa-pencil fa-4x my-2"></i> -->
                                    </div>
                                    Flights Tickets
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'Hotel_Booking' %}" class="w-50 pl-3 pb-4">
                            <div class="card border-0 border-bottom-blue shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <i class="fas fa-hotel fa-4x my-2"></i>
                                    </div>
                                    Hotels
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="d-flex">
                        <a href="{% url 'Holidays_Packages' %}" class="w-50 pr-3">
                            <div class="card border-0 border-bottom-yellow shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <!-- <i class="fas fa-umbrella-beach fa-code my-2"></i> -->
                                        <i class="fas fa-umbrella-beach fa-3x my-2" ></i>
                                    </div>
                                    Holiday Packages <p></p>
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'Visa_Enquiry' %}" class="w-50 pl-3">
                            <div class="card border-0 border-bottom-green shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <i class="fas fa-passport fa-3x my-2"></i>
                                    </div>
                                    Visa <br> Services <p></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="shape"></div>
                </div>
            </div>
        </div>
    </div>
    <svg style="pointer-events: none" class="wave" width="100%" height="50px" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 75">
        <defs>
            <style>
                .a {
                    fill: none;
                }
                
                .b {
                    clip-path: url(#a);
                }
                
                .c,
                .d {
                    fill: #f9f9fc;
                }
                
                .d {
                    opacity: 0.5;
                    isolation: isolate;
                }
            </style>
            <clipPath id="a">
                <rect class="a" width="1920" height="75"></rect>
            </clipPath>
        </defs>
        <title>wave</title>
        <g class="b">
            <path class="c" d="M1963,327H-105V65A2647.49,2647.49,0,0,1,431,19c217.7,3.5,239.6,30.8,470,36,297.3,6.7,367.5-36.2,642-28a2511.41,2511.41,0,0,1,420,48"></path>
        </g>
        <g class="b">
            <path class="d" d="M-127,404H1963V44c-140.1-28-343.3-46.7-566,22-75.5,23.3-118.5,45.9-162,64-48.6,20.2-404.7,128-784,0C355.2,97.7,341.6,78.3,235,50,86.6,10.6-41.8,6.9-127,10"></path>
        </g>
        <g class="b">
            <path class="d" d="M1979,462-155,446V106C251.8,20.2,576.6,15.9,805,30c167.4,10.3,322.3,32.9,680,56,207,13.4,378,20.3,494,24"></path>
        </g>
        <g class="b">
            <path class="d" d="M1998,484H-243V100c445.8,26.8,794.2-4.1,1035-39,141-20.4,231.1-40.1,378-45,349.6-11.6,636.7,73.8,828,150"></path>
        </g>
    </svg>
</header>
<br><br><br>


{% endblock %}

Voyage_Proj/templates/Voyage_LandingApp/Contact_email.html
{% block content %}
{% load static %}
<br>

<div class="container" style="background-color:#b49103; padding: 20px;">
    <h1>  <strong style="color: #f7f8fc;font-family:Libre Baskerville', serif ;"> Voyage Holidayz</strong> </h1>
    <div class="container text-center" style="color:white; padding:5%;">
        <h3>Traveller Details..</h3><hr>
        <p>First Nam                    : {{ firstname }} </p><hr>
        <p>Last Name                    : {{ lastname }}  </p><hr>
        <p>Email                        : {{ email }}</p><hr>
        <p>Phone Number                  : {{ phone }} </p><hr>
        <p>Message                      : {{ msg }} </p><hr>
       
    </div>
    
</div>










 

{% endblock %}


Voyage_Proj/templates/Voyage_LandingApp/Enquiry_Form.html
<!DOCTYPE html>
{% extends 'Voyage_LandingApp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="" id="Enquiry-Form">  
    

    <div class="row form-group">
        <legend class="text-center enquiry-head" style="font-family: 'Volkhov', serif;"> Enquiry</legend>
        {% if Form.errors %}
    {% for field in Form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in Form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
          <div class="col-sm">
              {% csrf_token %}
              <form action=""  method="post">
                        {% csrf_token %}
                        <!-- {{ Form.Full_Name|as_crispy_field }} -->
                        {{ Form.Full_Name }} <br>
            </div>
            <div class="col-sm">
                <!-- {{ Form.Email|as_crispy_field }} -->
                {{ Form.Email }} <br>
            </div>
            <div class="col-sm">
                <!-- {{ Form.Phone|as_crispy_field }} -->
                {{ Form.Phone }} <br>
            </div>
            <div class="col-sm">
                <!-- {{ Form.Journey_Date|as_crispy_field }} -->
                {{ Form.Journey_Date  }} <small class="text-muted">Date Of Journey</small>
            </div>
            <div class="col-sm">
                <!-- {{ Form.Destination|as_crispy_field }} -->
                {{ Form.Destination }} <br>
            </div>
            <div class="col-sm">
                <!-- {{ Form.Adults|as_crispy_field }} -->
                 {{ Form.Adults }}  <small class="text-muted">How Many People</small>
            </div>
            <div class="col-sm">
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </div>
    
            </form>
            </div>
    
    
      </div>
    

{% endblock %}

Voyage_Proj/templates/Voyage_LandingApp/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" /> 
    <!--  CSS FILE -->
    <link rel="stylesheet" href="{% static "css/voyage_style.css"  %}">
    <link rel="stylesheet" href="{% static "js/voyage.js"  %}">
    <link rel="stylesheet" href="{% static "main/gijgo.min.css" %}">
    <!-- flickity css  for sliding divs  -->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">

    <!-- javascript file -->
    <script src="{% static "js/voyage.js" %}"></script>
    <!-- bootstrap/css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <!-- font awesome -->
     <link rel="stylesheet"
     href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
     integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
     crossorigin="anonymous">
     <!-- google font for signu and signin -->
     <link href="https://fonts.googleapis.com/css2?family=Volkhov:wght@700&display=swap" rel="stylesheet">
    <!-- google font for brand -->
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap" rel="stylesheet">
    <!-- google fonts for wiki searched paragraph -->
    <link href="https://fonts.googleapis.com/css2?family=Quattrocento&display=swap" rel="stylesheet">



     <title>{% block title %} Voyage Holidayz {% endblock %}</title>
     <link rel="icon" href="{% static 'images/brand-flight.png' %}" type="image/gif" sizes="20x20">
</head>
<!--email above navbar  -->
<section>
  <div class="row bg text-center pt-2 fixed-top" style="background-color: #cc8e08;">
    <div class="col-md-6 pl-5">  
      <a href="https://api.whatsapp.com/send?phone=918130769090&text=" target="_blank" style="color: #ffffff;text-decoration:none;" target="_blank">
        <p> <img src="{% static 'images/whatsapp.png' %}" style="width: 30px;">  +91 81307 69090</p>
      </a>
    </div>
    <div class="col-md-4 text-center pr-5" style="margin-left:55px">
      <a href ="https://mail.google.com/mail/?view=cm&fs=1&to=voyageandholidayz@gmail.com" target="_blank"  style="color: #ffffff;text-decoration: none;">
         <p>&nbsp;&nbsp; <img src="{% static 'images/gmail.png' %}" alt="" style="width:30px">  voyageandholidayz@gmail.com </p>
      </a>
    </div>
  </div>
</section> 
<!--email above navbar end  -->








<body class="base-body">
<!-- Mega Navbar  -->
<div class="jumbotron banner-area" id="main-bnr" style="margin-top: 40px;padding-top:80px">
    <div class="container">
          <a href="{% url 'home' %}" id="brand-name"> Voyage 
            <img src="{% static 'images/brand-flight.png'%}" alt="" style="width:">
            Holidayz
          </a><br>

        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-custom bg"> 
                    <a class="navbar-brand" href="#">        </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active text-center">
                            <a class="nav-link" href="{% url 'home' %}">
                            <img class="text-center" src="{% static "images/home.png" %}" alt="" style="width: 40px;"> <br>
                            Home <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item text-center">
                            <a class="nav-link" href="{% url 'Domestic_Packages' %}">
                                <img class="text-center" src="{% static "images/domestic.png" %}" alt="" style="width: 40px;">
                                Domestic
                             </a>
                        </li>
                        <li class="nav-item text-center">
                            <a class="nav-link" href="{% url 'International_Packages' %}">
                                <img class="text-center" src="{% static "images/Destination.png" %}" alt="" style="width: 40px;">
                                International
                            </a>
                        </li>
                        <li class="nav-item text-center">
                            <a class="nav-link" href="{% url 'Flight_Booking' %}">
                                <img class="text-center" src="{% static "images/flights.png" %}" alt="" style="width: 40px;"><br>
                                Flights
                            </a>
                        </li>
                        <li class="nav-item text-center">
                          <a class="nav-link" href="{% url 'Contact' %}">
                              <img class="text-center" src="{% static "images/contact-us.png" %}" alt="" style="width: 40px;">
                              Contact
                          </a>
                        </li>
                        <li class="nav-item dropdown text-center">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <img class="text-center" src="{% static "images/more.png" %}" alt="" style="width: 40px;"> <br>
                              <span class="text-center">More</span> 
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{% url 'AboutUs' %}">Abouts</a>
                              <!-- <a class="dropdown-item" href="{% url 'Contact' %}">Contact Us</a> -->
                              <div class="dropdown-divider"></div>
                              {% if  user.get_username == 'voyage_admin' %}  
                              <a class="dropdown-item" href="{% url 'Holidays_Packages_Packages' %}">Hotel Package Upload</a>
                              {% endif %}
                            </div>
                          </li>
                      </ul>
                      <ul class="navbar-nav ml-auto"> 
                      {% if user.is_authenticated%}
                        <li class="nav-item"> 
                          <a class="nav-link text-center" href="{% url 'logout' %}"> 
                          <img class="text-center" src="{% static "images/logout.png" %}" alt="" style="width: 35px;"> <br>
                            LogOut 
                          </a> 
                        </li> 

                      {% else %}
                        <li class="nav-item"> 
                            <a class="nav-link text-center" href="{% url 'login' %}"  href="#sign-in-scrol"> 
                            <img class="text-center" src="{% static "images/login.png" %}" alt="" style="width: 35px;"> <br>
                              SignIn 
                            </a> 
                        </li>
                        <li class="nav-item"> 
                          <a class="nav-link text-center" href="{% url 'signup' %}"  href="#sign-in-scrol"> 
                          <img class="text-center" src="{% static "images/signup.png" %}" alt="" style="width: 35px;"> <br>
                            SignUp 
                          </a> 
                        </li>
                       {% endif %}
                      </ul> 

                      <!-- <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                      </form> -->
                    </div>
                  </nav>
            </div>
        </div>
    </div>
</div>

<!-- Mega Navbar ends here -->






<!-- content  -->
{% block content %}
{% endblock %}
<!-- content end  -->


<!-- footer div -->
 <!-- Copyright -->
 <footer id="footer-block-home" class="page-footer font-small unique-color-dark">
  <div class="footer-copyright text-center py-3" style="background-color: black;" id="all-in-one"> 
    <span style =color:white;> ©️ 2020 Copyright. All Rights Reserved AOCINC PVT. LTD.</span>
   <!-- <a id="brand-footer" href="https://mdbootstrap.com/"> AOCINC</a> -->
 </div>
 </footer>
 <!-- Copyright -->
 <!-- footer div end--> 
 
 



<!-- twak script for free chat with end user  -->
<!--Start of Tawk.to Script-->
<script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/5f7d4b1f4704467e89f54ba9/default';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);
  })();
  </script>
  <!--End of Tawk.to Script-->
<!-- twak js script end here -->



<!-- javascript/jquery cdn -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="{% static "main/gijgo.min.js" %}"></script>
<!-- flickity js script for sliding imgs/divs -->
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>


<!-- script for datepicker in For Enquiry form -->
<!-- <script>
  $(function () {
    $("#id_Journey_Date").datepicker({uiLibrary: 'bootstrap4',iconsLibrary: 'fontawesome'});
  })
</script> -->






</body>
</html>